development:
  adapter: redis
  url: <%= ENV.fetch("CABLE_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: <%= ENV["APPLICATION_NAME"] %>_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("CABLE_URL") %>
  channel_prefix: <%= ENV.fetch("CABLE_URL") %>



